on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
name: ci
run-name: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-build-test:
    uses: ./.github/workflows/lint-build-test.yml
      
  test:
    needs: [lint-build-test]
    runs-on: ubuntu-latest

    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v7
      
      - name: list directory
        run: ls -R