on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
name: ci
run-name: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-build-test:
    uses: ./.github/workflows/lint-build-test.yml

      