on:
    workflow_call

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: formatting check
        run: cargo fmt --all -- --check

      - name: clippy check
        run: cargo clippy --release --locked --workspace --all-features --all-targets -- -D clippy::all

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: pommo-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: pommo-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: pommo-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: pommo-windows-amd64.exe

    name: build and test on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - uses: Swatinem/rust-cache@v2

    - name: build
      run: cargo build --release --all-targets --target ${{ matrix.target }}
    
    - name: test
      run: cargo test --release --all-targets --target ${{ matrix.target }}

    - name: upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        path: target/${{ matrix.target }}/release/${{ matrix.os == 'windows-latest' && 'pommo.exe' || 'pommo' }}
        retention-days: 1