on:
  push:
    tags:
      - "v*.*.*"

name: release
run-name: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-build-test:
    uses: ./.github/workflows/lint-build-test.yml
    
  release:
    needs: [lint-build-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v8
    
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: pommo-*/pommo-*{.exe,}
          tag_name: ${{ github.ref_name }}
